config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  #Routes section presentation project
  get 'project/index'
  get 'project/about'
  get 'project/information'
  get 'project/terms-of-services'

  resources :topics
  resources :means
  get 'means/_form'

  get 'means/list'

  get 'user/show'

  resources :comunas
  resources :comunas, :id do
  	collection do
  		get 'comunidades'
  	end
  end

  resources :events

  resources :sites
  resources :sites do
  	collection do
  		get 'comunidades'
  	end
  end

  resources :communities

  resources :site_categories

  devise_for :users

  get 'home/index'  
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ActiveRecord::Base

	#Validación de los campos requeridos para crear un evento
	validates :name, :about, :fecha, :hora, :site_id, :presence => true

	#Asociación de un evento a un sitio
	belongs_to :site

	#Relationship with topics
	belongs_to :topic

	#Relationship with one or more topics
	#has_many :topicsevent
	#has_many :topic,
	#:trought => :topicsevent

	#Añadir avatar o imagen del evento
	has_attached_file :image, 
	:storage => :cloudinary,
	:path => ':id/:style/:filename',
	:cloudinary_credentials => Rails.root.join("config/cloudinary.yml")
	#styles: { medium: "300x300", thumb: "100x100" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  layout 'events/layoutEvent'

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :about, :fecha, :hora, :sitio, :estado, :image, :site_id, :topic_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form">
  <%= form_for(event) do |f| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field" align="left">
      <%= f.label :Nombre_del_Evento %>
      <%= f.text_field :name, placeholder: 'Nombre del Evento' %>      
    </div>

    <div class="field" align="left">
      <%= f.label :Descripción %>
      <%= f.text_area :about, placeholder: 'Descripción del Evento' %>
    </div>

    <p align="left">Selecciona el tipo de evento que realizarás</p>
    <div class="thumbnail">
      <div class="field">
        <%= f.label :Tipo_de_Evento %>
        <%= f.select(:topic_id, Topic.all.collect {|a| [a.name, a.id]},{prompt: 'seleccionar'},{} )%>
      </div>
    </div>

    <p>Escoge la fecha y hora de realización del evento</p>
    <div class="thumbnail">
      <div class="field">
        <%= f.label :Fecha %>
        <%= f.date_select :fecha %>
      </div>

      <div class="field">
        <%= f.label :Hora %>
        <%= f.time_select :hora %>
      </div>
    </div>

    <p >¿El lugar donde se realizará el evento ya se encuentra registrado en Maul Project?</p>

    <div class="thumbnail">
      <div class="field">
        <%= f.label :sitio %>
        <%= f.select(:site_id, Site.all.collect {|a| [a.name, a.id]},{prompt: 'seleccione un sitio'},{} )%>
      </div>
    </div>

    <!--<div class="field">
      <%= f.label :estado %>
      <%= f.text_field :estado %>
    </div>-->

    <p align="left">Añade una imagen a tu evento</p>
    <div class="field">
      <%= f.file_field :image %>
      <% if @event.image%>
        <%= image_tag @event.image.url(:thumb)%>
      <% end %>
     </div>    

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- File: Events edit. -->
<!-- ======================================== -->

	<div class="container">
		<% if user_signed_in? %>
			<h2 class="page-header" align="center">Actualización del Evento</h2>
			<%= render 'form', event: @event %>
		<% else %>
	      <div class="row" align="center">
	        <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
	        <div class="col-md-6">
	          <div class="thumbnail thumbnail-btn">
	              <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
	          </div>
	        </div>

	        <div class="col-md-6" >
	          <div class="thumbnail thumbnail-btn">
	            <a href="/users/sign_in">INICIAR SESIÓN</a>
	          </div>
	        </div>
	      </div>
	    <% end %>
	</div>

app/views/events/index.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- File: Events index -->
<!-- ======================================== -->


<!-- Breadcrumb navigation -->
  <div class="container">
    <ul class="breadcrumb page-header">
      <li><a href="/"><i class="fa fa-home"></i></a></li>
      <li><a href="/">Santiago de Cali</a></li>
      <li><a href="/events">Eventos</a></li>
    </ul>
  </div>

<!-- Index events -->
<div class="container" align="center">
  <h2 align="center">Eventos</h2>
  <%= link_to 'Crear Un Evento', new_event_path %>
  
  <table>
    <thead>
      <tr>
        <th> </th>        
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>            
      <% @events.each do |event| %>
        <tr>
          <td>
            <div class="row" align="center">
              <div class="col-md-5 ">
                <img class="img-responsive">
                <%= link_to image_tag(event.image.url, :width=>300, :heigth=>200), event %>
              </div>
              <div class="col-md-7 " align="left">
                <h4><%= link_to event.name, event %></h4>
                <p><strong>Resumen: </strong><%= event.about %></p>
                <p><strong>Fecha: </strong><%= event.fecha %></p>
              </div>
            </div>
            <hr>
          </td>

        </tr>
      <% end %>
        
    </tbody>
  </table>

  <!--
  <% if user_signed_in? %>

  <% else %>
    <div class="row" align="center">
      <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
      <div class="col-md-6">
        <div class="thumbnail thumbnail-btn">
            <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
        </div>
      </div>

      <div class="col-md-6" >
        <div class="thumbnail thumbnail-btn">
          <a href="/users/sign_in">INICIAR SESIÓN</a>
        </div>
      </div>
    </div>
  <% end %>
  -->

  <br>
</div>

app/views/events/new.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- File: Events new/create. -->
<!-- ======================================== -->


	<div class="container">
		<% if user_signed_in? %>
			<h2 class="page-header" align="center">Registro de Eventos</h2>
			
			<%= render 'form', event: @event %>
		<% else %>
	      <div class="row" align="center">
	        <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
	        <div class="col-md-6">
	          <div class="thumbnail thumbnail-btn">
	              <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
	          </div>
	        </div>

	        <div class="col-md-6" >
	          <div class="thumbnail thumbnail-btn">
	            <a href="/users/sign_in">INICIAR SESIÓN</a>
	          </div>
	        </div>
	      </div>
	    <% end %>
	</div>


<%= link_to 'Back', events_path %>
<p id="notice"><%= notice %></p>

app/views/events/show.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- File: Events show. -->
<!-- ======================================== -->

<section id="show_event">

  <!-- Breadcrumb navigation -->
  <div class="container">
    <ul class="breadcrumb page-header">
      <li><a href="/"><i class="fa fa-home"></i></a></li>
      <li><a href="/events">Eventos</a></li>
      <li><a href="/comunas/<%= @event.site.comuna.id %>"><%= @event.site.comuna.name %></a></li>
    </ul>
  </div>

  <div class="container">
      <h2><%= @event.name %></h2>
      <div class="well">
        <div class="row" align="center">
          <div class="col-md-offset-1 col-sm-offset-1 col-md-10 col-sm-10 col-xs-10">

            <div class="container" align="left">
              <p> <strong>Fecha: </strong><%= @event.fecha %>
              <strong>Hora:</strong> <%= @event.hora.strftime("%I:%M:%p") %>
              <strong>Sitio: </strong> <a href=<%= site_path %>> <%= @event.site.name %>  (<%= @event.site.adress %>) </p></a>
            </div>
            
            <div class="container thumbnail">
              <img class="img-responsive">
                <%= image_tag @event.image.url%>
              </img>
            </div>

            
              <div class="container" align="justify">
                <p> <%= @event.about %> </p>  
              </div>         

            <div class="container">
              <h4>Mapa del sitio</h4>
              <div class="maps-google">
                <iframe src= <%= @event.site.mapgoogle.gsub(/<iframe src="|" width="400" height="300" frameborder="0" style="border:0" allowfullscreen><|iframe>/,"") %> frameborder="0" style="border:0" ></iframe>
              </div>
            </div>

        </div>
      </div>      
    <!--
  <% if user_signed_in? %>

  <% else %>
    <div class="row" align="center">
      <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
      <div class="col-md-6">
        <div class="thumbnail thumbnail-btn">
            <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
        </div>
      </div>

      <div class="col-md-6" >
        <div class="thumbnail thumbnail-btn">
          <a href="/users/sign_in">INICIAR SESIÓN</a>
        </div>
      </div>
    </div>
  <% end %>
  -->
  </div>
  <%= link_to 'Modificar', edit_event_path(@event) %>
</section>