config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  #Routes section presentation project
  get 'project/index'
  get 'project/about'
  get 'project/information'
  get 'project/terms-of-services'

  resources :topics
  resources :means
  get 'means/_form'

  get 'means/list'

  get 'user/show'

  resources :comunas
  resources :comunas, :id do
  	collection do
  		get 'comunidades'
  	end
  end

  resources :events

  resources :sites
  resources :sites do
  	collection do
  		get 'comunidades'
  	end
  end

  resources :communities

  resources :site_categories

  devise_for :users

  get 'home/index'  
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ActiveRecord::Base	
	#Se declara la asociación, una comunidad esta referenciada a un sitio
	belongs_to :site
	#Se declara la asociación, una comunidad esta referenciada a una comuna
	belongs_to :comuna
	#Relationship with one or more events
	#belongs_to :event
	#Relationship with one or more topics (work areas)
	belongs_to :topic
	
	include ActiveModel::AttributeAssignment
	#Declaración para validar los campos obligatorios
	#attr_accessor => metodo getter/setter
	#attr_accessor :name
	validates :name, :about, :presence => true	

	has_attached_file :avatar,
	:storage => :cloudinary,
	:path => ':id/:style/:filename',
	:cloudinary_credentials => Rails.root.join("config/cloudinary.yml")
	#styles: { medium: "300x300", thumb: "100x100" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/communities_controller.rb
#Maul Project
#Author: Johnny Zapata Serna @samzapata
#File: Community controller

class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  layout 'communities/layoutCommunity'

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comunidades
    @communities = Community.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :about, :contacto, :email, :facebook, :twitter, :avatar, :site_id, :comuna_id, :topic_id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<div class="form">
<%= form_for(community) do |f| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>
      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field" align="left">
      <%= f.label :Seleccina_Una_Comuna %>
      <%= f.select(:comuna_id, Comuna.all.collect {|a| [a.name, a.id]},{prompt: 'seleccione una comuna'},{} )%>
      <!--<%= f.text_field :site_id %>-->
    </div>

    <div class="field" align="left">
      <%= f.label :Nombre %>
      <%= f.text_field :name, placeholder: 'Nombre de tu comunidad' %>
    </div>

    <div class="field" align="left">
       <%= f.label :Descripción %>
      <%= f.text_area :about, placeholder: 'Describe tu comunidad' %>
    </div>

    <div class="field" align="left">
      <%= f.label :Teléfono %>
      <%= f.text_field :contacto, placeholder: 'Número de contacto' %>
    </div>

    <div class="field" align="left">
      <%= f.label :Correo %>
      <%= f.text_field :email, placeholder: 'Email' %>
    </div>

    <p align="left">Añade los enlaces a tus redes sociales</p>

    <div class="field" align="left">
      <%= f.label :Facebook %>
      <%= f.text_field :facebook, placeholder: 'Perfil Facebook' %>
    </div>

    <div class="field" align="left">
      <%= f.label :Twitter %>
      <%= f.text_field :twitter, placeholder: 'Perfil Twitter' %>
    </div>

    <p>Selecciona un campo de acción</p>
    <div class="thumbnail">
      <div class="field">
        <%= f.label :Área %>
        <%= f.select(:topic_id, Topic.all.collect {|a| [a.name, a.id]},{prompt: 'Seleccionar'},{} )%>
      </div>
    </div>

    <p>¿El lugar donde se reune tu comunidad ya esta registrado en Maul?</p>
    <div class="thumbnail">
      <div class="field">
        <%= f.label :Sitio %>
        <%= f.select(:site_id, Site.all.collect {|a| [a.name, a.id]},{prompt: 'seleccione un sitio'},{} )%>
        <!--<%= f.text_field :site_id %>-->
      </div>
    </div>

    <p align="left">Agrega una imagen que identifique tu comunidad</p>

    <div class="field">
      <%= f.file_field :avatar %>
      <% if @community.avatar%>
        <%= image_tag @community.avatar.url(:thumb)%>
      <% end %>
     </div>    

    <div class="actions">
      <button>
      <%= f.submit %>
      </button>
    </div>

    <%= link_to 'Volver', communities_path %>  
<% end %>
</div>

app/views/communities/edit.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- Archivo: Sección para modificar la información de las comunidades registradas -->
<!-- ======================================== -->

<section id="modify_community">
	<div class="container">
		<% if user_signed_in?%>
			<h2 class="page-header" align="center">Actualiza Tu Comunidad</h2>
						
			<%= render 'form', community: @community %>
		<% else %>
	      <div class="row" align="center">
	        <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
	        <div class="col-md-6">
	          <div class="thumbnail thumbnail-btn">
	              <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
	          </div>
	        </div>

	        <div class="col-md-6" >
	          <div class="thumbnail thumbnail-btn">
	            <a href="/users/sign_in">INICIAR SESIÓN</a>
	          </div>
	        </div>
	      </div>
	    <% end %>
	</div>
</section>

app/views/communities/index.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- Archvio: Tabla de presentación de las comunidades -->
<!-- ======================================== -->

<!-- Breadcrumb navigation -->
  <div class="container">
    <ul class="breadcrumb page-header">
      <li><a href="/"><i class="fa fa-home"></i></a></li>
      <li><a href="/">Santiago de Cali</a></li>
      <li><a href="/communities">Comunidades</a></li>
    </ul>
  </div>

<div class="container" align="center">
  <h2 align="center">Comunidades</h2>
  <%= link_to 'Registrar Una Comunidad', new_community_path %>

    <!-- === Tab communities by comuna === -->
      <div class="container">
        <div class="thumbnail">
        <div id="subTab" class="btn-group" data-toogle="buttons-radio">
          <% Comuna.all.collect do |com| %>
            <a href="#comuna<%= com.id %>" class="btn active" data-toggle="tab">
              <span class="topics-community"><%= com.name %></span>
            </a>
          <% end -%>
        </div>
        </div>

        <!-- === Tab content === -->
        <div class="container">
          <div id="TabContent" class="tab-content">

            <!-- === Content all communities === -->
            <div id="index-community" class="tab-pane fade active in">
            <h4 class="">Todas las comunidades registradas en Maul Project</h4>
              <% Community.all.collect do |com| %>
                <div class="thumbnail col-lg-3 col-md-3">
                  <img class="img-responsive">
                    <%= link_to image_tag(com.avatar.url, :width=>200, :heigth=>200), com %>
                  <div class="caption">
                    <%= link_to com.name, com %>
                  </div>
                </div>
              <% end -%>
            </div>


            <!-- === Content communities by comuna === -->
            <% Comuna.all.collect do |com| %>
              <div class="tab-pane fade" id="comuna<%= com.id %>">
                <% Community.all.collect do |c| %>
                  <% if com.id === c.comuna_id %>
                    <div class="thumbnail col-lg-3 col-md-3">
                      <img class="img-responsive">
                      <%= link_to image_tag(c.avatar.url, :width=>200, :heigth=>200), c %>
                      <div class="caption">
                        <%= link_to c.name, c %>
                      </div>
                    </div>
                  <% end %>
                <% end -%>
              </div>
            <% end -%>
          </div>
        </div>

      </div>

</div>

app/views/communities/new.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- Archivo: Formulario para registrar una comunidad -->
<!-- ======================================== -->

<section id="register_community">
	<div class="container">
		<% if user_signed_in? %>
			<h2 class="page-header" align="center">Registra Tu Comunidad</h2>
			
			<%= render 'form', community: @community %>
		<% else %>
	      <div class="row" align="center">
	        <h4 class="page-header">Primero Debes Iniciar Sesión</h4>
	        <div class="col-md-6">
	          <div class="thumbnail thumbnail-btn">
	              <%= link_to "REGISTRARSE", new_user_registration_path, :class => 'navbar-link' %>
	          </div>
	        </div>

	        <div class="col-md-6" >
	          <div class="thumbnail thumbnail-btn">
	            <a href="/users/sign_in">INICIAR SESIÓN</a>
	          </div>
	        </div>
	      </div>
	    <% end %>
	</div>
</section> 

app/views/communities/show.html.erb
<!-- ======================================== -->
<!-- Maul Project - Una Ciudad, Una Comunidad -->
<!-- Autor: Johnny Zapata Serna -->
<!-- Archivo: Muestra una comunidad seleccionada -->
<!-- ======================================== -->


<!-- See community -->
<section id="show_community">

<!-- Breadcrumb navigation -->
<div class="container">
	<ul class="breadcrumb page-header">
		<li><a href="/"><i class="fa fa-home"></i></a></li>
		<li><a href="/communities">Comunidades</a></li>
		<li><a href="/comunas/<%= @community.comuna.id %>"><%= @community.comuna.name %></a></li>
		<li><a href="#"><%= @community.name %></a></li>
	</ul>
</div>

<div class="container">
		<h2 ><%= @community.name %></h2>
		<div class="well">
			<div class="row">
				<div class="col-lg-12">
					<div class="col-lg-8">
						<p><strong>Sobre la Comunidad</strong></p>
						<p> <%= @community.about %> </p>
						<p> <strong>Teléfono: </strong><%= @community.contacto %> </p>
						<p><strong>Email:</strong> <%= @community.email %> </p>
						<p><strong>Siguenos: </strong>															
								<a href= <%= @community.facebook %> ><i class="fa fa-2x fa-facebook-square"></i></a>
								<a href=<%= @community.twitter %>><i class="fa fa-2x fa-twitter-square"></i></a>
						</p>
						<p><strong>¿Donde estamos?</strong> <a href="/sites/<%=@community.site.id %>"> <%= @community.site.name %>  (<%= @community.site.adress %>) </p></a>
					</div>
					<div class="col-lg-4">
						<div class="thumbnail">
							<img class="img-responsive">
							<%= image_tag @community.avatar.url %>
						</div>
					</div>
			  	</div>
			</div>
	  	</div>
	  	<%= link_to 'Modificar', edit_community_path(@community) %> |
		<%= link_to 'Volver', communities_path %>
</div>
</section>

<p id="notice"><%= notice %></p>